name: Build Android APK

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          wget \
          curl \
          unzip \
          zip \
          autoconf \
          automake \
          libtool \
          libtool-bin \
          libltdl-dev \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libssl-dev \
          libffi-dev \
          libsqlite3-dev \
          libbz2-dev \
          libreadline-dev \
          llvm \
          xz-utils \
          tk-dev \
          libxml2-dev \
          libxmlsec1-dev \
          liblzma-dev \
          m4 \
          gettext
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install \
          buildozer==1.5.0 \
          cython==0.29.36 \
          kivy
    
    - name: Build Android APK
      working-directory: ./mobile-noted
      run: |
        # Set environment variables for Android build
        export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
        export ANDROID_NDK_HOME=$HOME/.buildozer/android/platform/android-ndk
        export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
        
        # Ensure libtool is properly configured for autotools
        export ACLOCAL_PATH="/usr/share/aclocal:${ACLOCAL_PATH}"
        autoreconf --version
        libtoolize --version
        
        # Build the APK
        buildozer android debug
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: mobile-noted-apk
        path: ./mobile-noted/bin/*.apk
        
    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          ./mobile-noted/.buildozer/
          !./mobile-noted/.buildozer/android/platform/android-sdk/
          !./mobile-noted/.buildozer/android/platform/android-ndk/